export const categories = [
    {id: 0, type: 'All'},
    {id: 1, type: 'Music'},
    {id: 2, type: 'Food'},
    {id: 3, type: 'Travel'},
    {id: 4, type: 'Health and Fitness'},
    {id: 5, type: 'Lifestyle'},
    {id: 6, type: 'Photography'},
    {id: 7, type: 'Personal'},
    {id: 8, type: 'Business'},
    {id: 9, type: 'Art and Design'},
    {id: 10, type: 'Sports'},
    {id: 11, type: 'News'},
    {id: 12, type: 'Religion'},
    {id: 13, type: 'Movie'},
    {id: 14, type: 'Political'},
    {id: 15, type: 'Personal Finance'},
    {id: 16, type: 'Fashion and Beauty'},
    {id: 17, type: 'DIY Craft'},
    {id: 18, type: 'Parenting'},
    {id: 19, type: 'Interior Design'},
    {id: 20, type: 'Book and Writing'},
    {id: 21, type: 'Programming'},
]

export const top20Categories = [
    {id: 1, label:  'Music'},
    {id: 2, label:  'Food'},
    {id: 3, label:  'Travel'},
    {id: 4, label:  'Health and Fitness'},
    {id: 5, label:  'Lifestyle'},
    {id: 6, label:  'Photography'},
    {id: 7, label:  'Personal'},
    {id: 8, label:  'Business'},
    {id: 9, label:  'Art and Design'},
    {id: 10, label:  'Sports'},
    {id: 11, label:  'News'},
    {id: 12, label:  'Religion'},
    {id: 13, label:  'Movie'},
    {id: 14, label:  'Political'},
    {id: 15, label:  'Personal Finance'},
    {id: 16, label:  'Fashion and Beauty'},
    {id: 17, label:  'DIY Craft'},
    {id: 18, label:  'Parenting'},
    {id: 19, label:  'Interior Design'},
    {id: 20, label:  'Book and Writing'},
    {id: 21, label:  'Programming'},
  ];